# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b81157195c0f44cf51aacd8da22490bc85c916317eeac7d95572c99e4489b740e06186bb1a7c0b36408c1fbc25ae953816981645f2897949b77980dc5f2b2c34

test:
  secret_key_base: 32476edfeda5866c61b88c2bb86e6750f2bce73661f8fc9ffd15cd40a404a511ae67b01797606979a47bcc20bd4df3480150e950d108ebdf6c32d5f1ed833f6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
